export { HeroSection } from './HeroSection';
export { StakeholdersSection } from './StakeholdersSection';
export { LicenseStepsSection } from './LicenseStepsSection';
export { JoinLasismaSection } from './JoinLasismaSection';
export { InitiativesSection } from './InitiativesSection';
export { GruCardsSection } from './GruCardsSection';
export { ReportSection } from './ReportSection';
export { NewsSection } from './NewsSection';
export { MvhmSection } from './MvhmSection';
